name: Lint
on: push
jobs:
  lint:
    name: Lint, Test and Build
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint